"""modif customer table

Revision ID: 06f0f64f2dc7
Revises: 843df0b06e19
Create Date: 2024-09-03 16:06:08.191006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f0f64f2dc7'
down_revision: Union[str, None] = '843df0b06e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_image', table_name='customers')
    op.drop_column('customers', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_customers_image', 'customers', ['image'], unique=False)
    # ### end Alembic commands ###
