"""init revision

Revision ID: 1b0d69923257
Revises: 
Create Date: 2024-09-04 09:28:50.681578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0d69923257'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothes_id'), 'clothes', ['id'], unique=False)
    op.create_index(op.f('ix_clothes_type'), 'clothes', ['type'], unique=False)
    op.add_column('payementHistory', sa.Column('date', sa.String(), nullable=True))
    op.add_column('payementHistory', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('payementHistory', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('payementHistory', sa.Column('payment_method', sa.String(), nullable=True))
    op.create_index(op.f('ix_payementHistory_amount'), 'payementHistory', ['amount'], unique=False)
    op.create_index(op.f('ix_payementHistory_comment'), 'payementHistory', ['comment'], unique=False)
    op.create_index(op.f('ix_payementHistory_date'), 'payementHistory', ['date'], unique=False)
    op.create_index(op.f('ix_payementHistory_payment_method'), 'payementHistory', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payementHistory_payment_method'), table_name='payementHistory')
    op.drop_index(op.f('ix_payementHistory_date'), table_name='payementHistory')
    op.drop_index(op.f('ix_payementHistory_comment'), table_name='payementHistory')
    op.drop_index(op.f('ix_payementHistory_amount'), table_name='payementHistory')
    op.drop_column('payementHistory', 'payment_method')
    op.drop_column('payementHistory', 'comment')
    op.drop_column('payementHistory', 'amount')
    op.drop_column('payementHistory', 'date')
    op.drop_index(op.f('ix_clothes_type'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_id'), table_name='clothes')
    op.drop_table('clothes')
    # ### end Alembic commands ###
