"""modif customer table

Revision ID: 32f1ec797d3f
Revises: 
Create Date: 2024-09-03 17:14:31.885615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f1ec797d3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clothes_id'), 'clothes', ['id'], unique=False)
    op.create_index(op.f('ix_clothes_type'), 'clothes', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clothes_type'), table_name='clothes')
    op.drop_index(op.f('ix_clothes_id'), table_name='clothes')
    op.drop_table('clothes')
    # ### end Alembic commands ###
