"""Adding the location to the events table

Revision ID: 50d6c78de892
Revises: fd52a4fec7a2
Create Date: 2024-09-02 22:18:51.530147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d6c78de892'
down_revision: Union[str, None] = 'fd52a4fec7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location_x', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_location_x'), 'events', ['location_x'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_location_x'), table_name='events')
    op.drop_column('events', 'location_x')
    # ### end Alembic commands ###
