"""start database

Revision ID: 74b274d867d5
Revises: 
Create Date: 2024-09-04 09:18:51.028427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b274d867d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_duration'), 'events', ['duration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_duration'), table_name='events')
    op.drop_column('events', 'duration')
    # ### end Alembic commands ###
