"""modif customer table

Revision ID: 843df0b06e19
Revises: 1eca9f2a71f7
Create Date: 2024-09-03 15:57:27.850740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843df0b06e19'
down_revision: Union[str, None] = '1eca9f2a71f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('image', sa.String(), nullable=True))
    op.create_index(op.f('ix_customers_image'), 'customers', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_image'), table_name='customers')
    op.drop_column('customers', 'image')
    # ### end Alembic commands ###
