"""init database

Revision ID: a94fe3afa1a0
Revises: 
Create Date: 2024-09-04 10:18:09.338417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94fe3afa1a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_clothesType', table_name='customers')
    op.drop_column('customers', 'clothesType')
    op.add_column('events', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_duration'), 'events', ['duration'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_duration'), table_name='events')
    op.drop_column('events', 'duration')
    op.add_column('customers', sa.Column('clothesType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_customers_clothesType', 'customers', ['clothesType'], unique=False)
    # ### end Alembic commands ###
