"""start database

Revision ID: c1c1068f4a1e
Revises: b0276e7f4f56
Create Date: 2024-09-04 10:05:27.934115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c1068f4a1e'
down_revision: Union[str, None] = 'b0276e7f4f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_clothesType', table_name='customers')
    op.drop_column('customers', 'clothesType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('clothesType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_customers_clothesType', 'customers', ['clothesType'], unique=False)
    # ### end Alembic commands ###
