"""modif customer table

Revision ID: c5644dde6767
Revises: 068c9ada33f5
Create Date: 2024-09-03 15:27:35.271086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5644dde6767'
down_revision: Union[str, None] = '068c9ada33f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('birthdate', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('astrologicalSign', sa.String(), nullable=True),
    sa.Column('clothesType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_astrologicalSign'), 'customers', ['astrologicalSign'], unique=False)
    op.create_index(op.f('ix_customers_birthdate'), 'customers', ['birthdate'], unique=False)
    op.create_index(op.f('ix_customers_clothesType'), 'customers', ['clothesType'], unique=False)
    op.create_index(op.f('ix_customers_description'), 'customers', ['description'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_gender'), 'customers', ['gender'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_password'), 'customers', ['password'], unique=False)
    op.create_index(op.f('ix_customers_surname'), 'customers', ['surname'], unique=False)
    op.create_foreign_key(None, 'encounters', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'payementHistory', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payementHistory', type_='foreignkey')
    op.drop_constraint(None, 'encounters', type_='foreignkey')
    op.drop_index(op.f('ix_customers_surname'), table_name='customers')
    op.drop_index(op.f('ix_customers_password'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_gender'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_description'), table_name='customers')
    op.drop_index(op.f('ix_customers_clothesType'), table_name='customers')
    op.drop_index(op.f('ix_customers_birthdate'), table_name='customers')
    op.drop_index(op.f('ix_customers_astrologicalSign'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
