"""modif customer table

Revision ID: d3ff6311d487
Revises: 
Create Date: 2024-09-03 16:44:19.619290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ff6311d487'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payementHistory', sa.Column('date', sa.String(), nullable=True))
    op.add_column('payementHistory', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('payementHistory', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('payementHistory', sa.Column('payment_method', sa.String(), nullable=True))
    op.create_index(op.f('ix_payementHistory_amount'), 'payementHistory', ['amount'], unique=False)
    op.create_index(op.f('ix_payementHistory_comment'), 'payementHistory', ['comment'], unique=False)
    op.create_index(op.f('ix_payementHistory_date'), 'payementHistory', ['date'], unique=False)
    op.create_index(op.f('ix_payementHistory_payment_method'), 'payementHistory', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payementHistory_payment_method'), table_name='payementHistory')
    op.drop_index(op.f('ix_payementHistory_date'), table_name='payementHistory')
    op.drop_index(op.f('ix_payementHistory_comment'), table_name='payementHistory')
    op.drop_index(op.f('ix_payementHistory_amount'), table_name='payementHistory')
    op.drop_column('payementHistory', 'payment_method')
    op.drop_column('payementHistory', 'comment')
    op.drop_column('payementHistory', 'amount')
    op.drop_column('payementHistory', 'date')
    # ### end Alembic commands ###
