import "./globals.css";
import { Inter } from "next/font/google";


import NavBar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Soul-Connection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="{inter.className} text-[#334760] sticky top-0">
        <div className="min-h-screen bg-[#f5f6fa]">
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
