import "./globals.css";
import { Inter } from "next/font/google";
import {
  Disclosure,
  DisclosureButton,
  DisclosurePanel,
  Menu,
  MenuButton,
  MenuItem,
  MenuItems,
} from "@headlessui/react";
import { Bars3Icon, BellIcon, XMarkIcon } from "@heroicons/react/24/outline";

import NavBar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Soul-Connection",
  description: "Generated by create next app",
};

const user = {
  name: "Tom Cook",
  email: "tom@example.com",
  imageUrl:
    "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
};
const navigation = [
  { name: "Dashboard", href: "/", current: true },
  { name: "Coaches", href: "/coaches", current: false },
  { name: "Customers", href: "/customers", current: false },
  { name: "Tips", href: "/tips", current: false },
  { name: "Events", href: "/events", current: false },
];
const userNavigation = [
  { name: "Your Profile", href: "profil" },
  { name: "Settings", href: "#" },
  { name: "Sign out", href: "#" },
];

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sticky: React.CSSProperties = { position: "sticky", top: "0" };
  return (
    <html lang="en">
      <body className="{inter.className} text-[#334760]">
        <div className="min-h-screen bg-[#f5f6fa]">
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
